artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/2dff19f66b2c4d54b843c9ea3ce30424/artifacts
end_time: 1782931467074
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 2dff19f66b2c4d54b843c9ea3ce30424
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1782931382119
status: 3
tags: []
user_id: root
