artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/5f2703351dd1448f8f6c15cc12398fbc/artifacts
end_time: 1780864431908
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 5f2703351dd1448f8f6c15cc12398fbc
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1780864416481
status: 3
tags: []
user_id: root
