artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/bae896d5cd48474b9dc1bc9cc702e5dc/artifacts
end_time: 1781296913231
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: bae896d5cd48474b9dc1bc9cc702e5dc
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1781296905703
status: 3
tags: []
user_id: root
