artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/83d054ff91cb41e093d51d83e6f9facf/artifacts
end_time: 1781296697712
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 83d054ff91cb41e093d51d83e6f9facf
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1781296689834
status: 3
tags: []
user_id: root
