artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/0c11b71b34e54a2cad77c67f7ef94309/artifacts
end_time: 1780868991907
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 0c11b71b34e54a2cad77c67f7ef94309
run_name: two_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1780868967268
status: 3
tags: []
user_id: root
