artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/6f2ad64307844652bddd5eef89d9c082/artifacts
end_time: 1782931022017
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 6f2ad64307844652bddd5eef89d9c082
run_name: one_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782931009172
status: 3
tags: []
user_id: root
