artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/ac1fd63c6ae046059da434ed6fe7c2d6/artifacts
end_time: 1780864416412
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: ac1fd63c6ae046059da434ed6fe7c2d6
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1780864407701
status: 3
tags: []
user_id: root
