artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/956351ab1b564faf995d3863ccc75991/artifacts
end_time: 1781301950232
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 956351ab1b564faf995d3863ccc75991
run_name: autoencoder_long_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1781301942809
status: 3
tags: []
user_id: root
