artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/22f082c76c3d4ed48c44ce5d3a85501d/artifacts
end_time: 1782931036340
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: 22f082c76c3d4ed48c44ce5d3a85501d
run_name: two_layer_fcnn_test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1782931022022
status: 3
tags: []
user_id: root
