artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/a450d0caabb5429096f99d7a088bb68e/artifacts
end_time: 1781297189085
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: a450d0caabb5429096f99d7a088bb68e
run_name: simple_network_training
source_name: ''
source_type: 4
source_version: ''
start_time: 1781297182069
status: 3
tags: []
user_id: root
