artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/e9eb3ebd439f4a23b19508a1480297c7/artifacts
end_time: 1781358151120
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: e9eb3ebd439f4a23b19508a1480297c7
run_name: gradient_reversal_gan
source_name: ''
source_type: 4
source_version: ''
start_time: 1781358135043
status: 3
tags: []
user_id: root
