artifact_uri: file:///workspaces/neural-networks-fundamentals/.laborantum/mlflow_logs/767078934857844539/cae09e6060584ee3a0490c03b883576a/artifacts
end_time: 1781357292097
entry_point_name: ''
experiment_id: '767078934857844539'
lifecycle_stage: active
run_id: cae09e6060584ee3a0490c03b883576a
run_name: gradient_reversal_gan
source_name: ''
source_type: 4
source_version: ''
start_time: 1781357270287
status: 3
tags: []
user_id: root
